name: PlatformIO CI

on: [push]

jobs:
  metadata:
    runs-on: ubuntu-latest
    name: Parse config metadata
    outputs:
      meta_json: ${{ steps.parse_yaml.outputs.metadata }}
      # repo: ${{ fromJson(steps.parse_yaml.outputs.metadata).repo }}
      # revision: ${{ fromJson(steps.parse_yaml.outputs.metadata).revision }}
      build_matrix: "${{ steps.parse_yaml.outputs.metadata.build }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Read metadata from yaml file
    #   id: parse_yaml
    #   # uses: pietrobolcato/action-read-yaml@1.1.0
    #   uses: hyorman/action-read-yaml@set-array-output
    #   with:
    #     config: meta.yaml
    
    # - name: print stuff out
    #   run: |
    #     echo "${{ steps.parse_yaml.outputs }}"
    #     echo "${{ steps.parse_yaml.outputs.repo }}"
    #     echo "${{ steps.parse_yaml.outputs.revision }}"
    #     echo "${{ steps.parse_yaml.outputs.build }}"
    #     echo "${{ steps.parse_yaml.outputs.build.array }}"
    
    # - name: Get SDK Version from config
    #   id: parse_yaml
    #   uses: mikefarah/yq@master
    #   with:
    #     cmd: yq '' 'meta.yaml'

    - name: Install yaml2json
      run: python3 -m pip install remarshal

    - name: Read metadata from yaml file
      id: parse_yaml
        # echo "build_matrix=$(yaml2json 'meta.yaml' | jq -c .)" >> $GITHUB_ENV
      run: |
        echo "metadata=$(yaml2json 'meta.yaml')" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: metadata
    env:
      FIRMWARE_REPO: ${{ fromJson(needs.metadata.outputs.meta_json).repo }}
      VERSION_REF: ${{ fromJson(needs.metadata.outputs.meta_json).revision }}
      # BUILD_MATRIX: ${{ }}
    #   VERSION_REF: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    strategy:
        matrix: 
          include: ${{ fromJson(needs.metadata.outputs.meta_json).build }}
            # - env: pico
            #   bin_ext: uf2

    steps:
    - name: Check out HayBox repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.FIRMWARE_REPO }}
        ref: ${{ env.VERSION_REF }}

    - name: Check out config repo
      uses: actions/checkout@v3
      with:
        path: config/test_device
    
    - name: Check some stuff
      run: |
        ls -lah
        ls -lah config
        ls -lah ..

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install PlatformIO
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install --upgrade platformio

    # - name: Build ${{ matrix.env }} env
    #   run: |
    #     pio run -e ${{ matrix.env }}
    #     mkdir -p ${{ matrix.env }}
    #     cp .pio/build/${{ matrix.env }}/firmware.${{ matrix.bin_ext }} ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}

    # - name: Publish ${{ matrix.env }} artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}
    #     path: ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}

    # - name: Upload binaries to release
    #   uses: softprops/action-gh-release@v1
    #   if: github.ref_type == 'tag'
    #   with:
    #     files: ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}
