name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      UPSTREAM_REPO: JonnyHaystack/HayBox
      VERSION_REF: v2.4.0
    #   VERSION_REF: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    strategy:
        matrix:
          include:
            - env: pico
              bin_ext: uf2

    steps:
    - name: Check out HayBox repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.UPSTREAM_REPO }}
        ref: ${{ env.VERSION_REF }}
        path: HayBox

    - name: Check out config repo
      uses: actions/checkout@v3
      with:
        path: config/test_device
    
    - name: Check some stuff
      run: |
        ls -lah
        ls -lah config
        ls -lah ..

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install PlatformIO
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install --upgrade platformio

    # - name: Build ${{ matrix.env }} env
    #   run: |
    #     pio run -e ${{ matrix.env }}
    #     mkdir -p ${{ matrix.env }}
    #     cp .pio/build/${{ matrix.env }}/firmware.${{ matrix.bin_ext }} ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}

    # - name: Publish ${{ matrix.env }} artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}
    #     path: ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}

    # - name: Upload binaries to release
    #   uses: softprops/action-gh-release@v1
    #   if: github.ref_type == 'tag'
    #   with:
    #     files: ${{ matrix.env }}/HayBox-${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}
